rango/urls.py
from django.urls import path
from rango import views
app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('add_category/', views.add_category, name='add_category'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),

    path('movies/', views.get_movie, name='movie_detail'),
    path('movies/<int:movie_id>/', views.get_movie, name='movie_detail'),
    path('movies/<int:movie_id>/<int:page>', views.get_movie, name='movie_detail'),
    path('movies/<int:movie_id>/review', views.add_movie_review, name='add_movie_review'),
    path('movies/top/', views.get_top_movies, name='top_movies'),
    path('movies/top/<int:page>/', views.get_top_movies, name='top_movies'),
    path('movies/latest/', views.get_latest_movies, name='latest_movies'),
    path('movies/latest/<int:page>/', views.get_latest_movies, name='latest_movies'),
    path('movies/search/', views.search_movies, name='movie_search'),
    path('movies/search/<str:keyword>/', views.search_more_movies, name='movie_search'),
    path('movies/search/<str:keyword>/<int:page>/', views.search_more_movies, name='movie_search'),

    path('genres/', views.get_movies_by_genre, name='genres'),
    path('genres/<str:genre>/', views.get_movies_by_genre, name='genres'),
    path('genres/<str:genre>/<int:page>/', views.get_movies_by_genre, name='genres'),

    path('reviews/', views.get_popular_reviews, name='popular_reviews'),
    path('reviews/popular/', views.get_popular_reviews, name='popular_reviews'),
    path('reviews/popular/<int:page>', views.get_popular_reviews, name='popular_reviews'),
    path('reviews/like/', views.like_review, name='like_review'),
    path('reviews/<str:user_name>/', views.get_reviews_by_user, name='reviews'),
    path('reviews/<str:user_name>/<int:page>/', views.get_reviews_by_user, name='reviews_page'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    NAME_LENGTH = 128

    name = models.CharField(max_length=NAME_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    TITLE_LENGTH = 128

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username


class Genre(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, default='')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Genre, self).save(*args, **kwargs)


class Movie(models.Model):
    genres = models.CharField(max_length=100)
    imdb_id = models.CharField(max_length=10)
    name = models.CharField(max_length=150)
    runtime = models.IntegerField(default=-1)
    countries = models.CharField(max_length=200)
    directors = models.CharField(max_length=200)
    actors = models.CharField(max_length=500)
    description = models.CharField(max_length=1000)
    pic_url = models.CharField(max_length=200)
    release_year = models.IntegerField(null=True)
    rating = models.FloatField(default=-1)


class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=5000)
    time = models.DateTimeField(null=True)
    likes = models.IntegerField(default=0)
    rating = models.FloatField(default=0)

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_LENGTH, help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_LENGTH, help_text='Please enter the title of the page.')
    url = forms.URLField(max_length=200, help_text='Please enter the URL of the page.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            cleaned_data['url'] = f'http://{url}'

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
import json
import re
from datetime import datetime, timezone

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from rango.forms import CategoryForm, PageForm
from rango.models import Category, Page, Genre, Movie, Review, UserProfile


def index(request):
    carousel_movies = Movie.objects.all().order_by('-rating')[:5]

    editor_picks = Movie.objects.all().order_by('-release_year')[:6]

    return render(request, 'rango/index.html', context={
        'carousel_movies': carousel_movies,
        'editor_picks': editor_picks
    })


def about(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    return render(request, 'rango/about.html', context={
        'visits': visits
    })


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)

        context_dict['category'] = category
        context_dict['pages'] = Page.objects.filter(category=category)
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/')
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None

    if not category: return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        user = User.objects.create_user(
            username=username,
            email=email,
            password=password
        )
        user.save()

        profile = UserProfile.objects.create(user=user)
        profile.save()

        return redirect(reverse('rango:login'))
    else:
        return render(request, 'rango/register.html')


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val: val = default_val

    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))

    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def get_paginator(data_list, page):
    p = Paginator(data_list, 12)
    paginator = p.page(page)

    if p.num_pages > 11:
        if page + 5 > p.num_pages:
            page_range = range(p.num_pages - 10, p.num_pages + 1)
        elif page - 5 < 1:
            page_range = range(1, 12)
        else:
            page_range = range(page - 5, page + 5 + 1)
    else:
        page_range = p.page_range

    return page_range, paginator


def get_movie_list_response(request, data_list, page, list_title, url_prefix=None):
    page_range, paginator = get_paginator(data_list, page)

    if not url_prefix:
        url_prefix = re.findall('(.*/)\d+', request.path)
        url_prefix = url_prefix[0] if url_prefix else request.path

    return render(request, 'rango/movie.html', context={
        'list_title': list_title,
        'movie_page': paginator,
        'page_range': page_range,
        'current_page': page,
        'url_prefix': url_prefix
    })


def get_movie(request, movie_id, page=1):
    movie = Movie.objects.get(id=movie_id)
    reviews = Review.objects.filter(movie=movie).order_by('-likes')

    genres = movie.genres.split(',')
    countries = movie.countries.replace(',', '/')
    directors = movie.directors.replace(',', '/')
    actors = movie.actors.replace(',', '/')

    page_range, paginator = get_paginator(reviews, page)

    res = re.findall('\d+', request.path)
    url_prefix = '/rango/movies/%s/' % res[0]

    print(request.user.username)

    return render(request, 'rango/movie_detail.html', context={
        'movie': movie,
        'genres': genres,
        'countries': countries,
        'directors': directors,
        'actors': actors,
        'review_page': paginator,
        'page_range': page_range,
        'current_page': page,
        'url_prefix': url_prefix,
        'is_logged_in': request.user.username != ''
    })


def add_movie_review(request, movie_id):
    if not request.user.username:
        return HttpResponse(
            json.dumps({
                'success': False,
                'msg': 'login required'
            }),
            content_type='application/json'
        )

    if request.method == 'POST' and request.body:
        data = json.loads(request.body)
        movie = Movie.objects.get(id=movie_id)

        title = data.get('title')
        content = data.get('content')
        rating = data.get('rating')
        review_time = datetime.now(tz=timezone.utc)

        rating = 2 * int(re.findall('\d', rating)[0])

        review = Review.objects.create(
            movie=movie,
            user=request.user,
            title=title,
            content=content,
            time=review_time,
            likes=0,
            rating=rating
        )

        review.save()

        return HttpResponse(
            json.dumps({
                'success': True,
                'review_id': review.id,
                'rating': rating,
                'username': request.user.username
            }),
            content_type='application/json'
        )
    else:
        return HttpResponse(
            json.dumps({'success': False}),
            content_type='application/json'
        )


def get_top_movies(request, page=1):
    all_movies = Movie.objects.filter().order_by('-rating')
    return get_movie_list_response(request, all_movies, page, 'TOP 250 MOVIES')


def get_latest_movies(request, page=1):
    all_movies = Movie.objects.filter().order_by('-release_year')
    return get_movie_list_response(request, all_movies, page, 'LATEST MOVIES')


def search_movies(request):
    keyword = request.GET.get('keyword')

    results = Movie.objects.filter(name__icontains=keyword).order_by('-rating')

    return get_movie_list_response(request, results, 1, 'RELATED MOVIES', request.path + keyword + '/')


def search_more_movies(request, keyword, page=1):
    results = Movie.objects.filter(name__icontains=keyword).order_by('-rating')

    return get_movie_list_response(request, results, page, 'RELATED MOVIES')


def get_movies_by_genre(request, genre=None, page=1):
    if not genre:
        genres = Genre.objects.all()

        return render(request, 'rango/genres.html', context={'genres': genres})

    movie_list = Movie.objects.filter(genres__contains=genre).order_by('-rating')

    return get_movie_list_response(request, movie_list, page, genre.upper() + ' MOVIES')


def get_review_list_response(request, data_list, page, list_title, url_prefix=None, user=None,):
    page_range, paginator = get_paginator(data_list, page)

    if not url_prefix:
        url_prefix = re.findall('(.*/)\d+', request.path)
        url_prefix = url_prefix[0] if url_prefix else request.path

    return render(request, 'rango/reviews.html', context={
        'review_page': paginator,
        'page_range': page_range,
        'current_page': page,
        'url_prefix': url_prefix,
        'user': user,
        'list_title': list_title
    })


def get_popular_reviews(request, page=1):
    all_reviews = Review.objects.filter().order_by('-likes').filter()
    return get_review_list_response(request, all_reviews, page, 'POPULAR REVIEWS')


def get_reviews_by_user(request, user_name, page=1):
    user = User.objects.filter(username=user_name).first()

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Add a Category
{% endblock %}

{% block body_block %}
  <h1>Add a Category</h1>
  <div>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
      {% endfor %}
      <input type="submit" name="submit" value="Create Category"/>
    </form>
  </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Add a Page
{% endblock %}

{% block body_block %}
  <h1>Add a Page</h1>
  <div>
    <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br>
        {{ field }}<br>
      {% endfor %}
      <input type="submit" name="submit" value="Create Page"/>
    </form>
  </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>
      The Waves -
      {% block title_block %}
        Select movies, exchange thoughts
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/4.6.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block js_block %}
    {% endblock %}
  </head>
  <body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">The Waves</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:genres' %}">Genres</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:top_movies' %}">Ranking</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:latest_movies' %}">Latest</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:popular_reviews' %}">Reviews</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'rango:movie_search' %}" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="keyword" required>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% if user.is_authenticated %}
          <a class="btn btn-primary ml-2" href="{% url 'rango:logout' %}">Logout</a>
        {% else %}
          <a class="btn btn-primary ml-2" href="{% url 'rango:login' %}">Sign in</a>
        {% endif %}
      </div>
    </nav>
    <!-- Navbar -->

    <!-- Body -->
    {% block body_block %}
    {% endblock %}
    <!-- Body -->

    <!-- Footer -->
    <footer class="page-footer font-small blue">
      <div class="footer-copyright text-center py-3">© 2021 The Waves, all rights reserved</div>
    </footer>
    <!-- Footer -->
  </body>
</html>

templates/rango/movie_detail.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{ movie.name }}
{% endblock %}

{% block js_block %}
  <script src="{% static 'js/rango.js' %}" type="application/javascript"></script>
  <script src="{% static 'js/reviews.js' %}" type="application/javascript"></script>
{% endblock %}

{% block body_block %}
  <div class="movie-info">
    <h1 class="display-4">{{ movie.name }}</h1>

    <div class="row">
      <div class="col-md-4">
        <img src="{{ MEDIA_URL }}movie_covers/{{ movie.imdb_id }}.jpg" alt="" class="poster">
      </div>

      <div class="col-md-8">
        <ul class="genres-bar">
          {% for genre in genres %}
            <a href="{% url 'rango:genres' %}{{ genre }}" class="genre">
              <span class="badge rounded-pill bg-primary">{{ genre }}</span>
            </a>
          {% endfor %}
        </ul>

        <div class="list-group">
          <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Actors</h5>
            </div>
            <p class="mb-1">{{ actors }}</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Directors</h5>
            </div>
            <p class="mb-1">{{ directors }}</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Countries</h5>
            </div>
            <p class="mb-1">{{ countries }}</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Runtime</h5>
            </div>
            <p class="mb-1">{{ movie.runtime }} minutes</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Plot</h5>
            </div>
            <p class="mb-1">{{ movie.description }}</p>
          </a>
        </div>

      </div>
    </div>

    <hr>

    <div class="my-review">
      <div class="row">
        <div class="col-md-1"></div>
        <input type="text" class="col-md-8 title-box" placeholder="Title">
        <div class="col-md-2">
          <div class="star-rating">
            <fieldset>
              <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="Outstanding">5 stars</label>
              <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Very Good">4 stars</label>
              <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Good">3 stars</label>
              <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Poor">2 stars</label>
              <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Very Poor">1 star</label>
            </fieldset>
          </div>
        </div>
        <div class="col-md-1"></div>
      </div>
      <div class="row">
        <div class="col-md-1"></div>
        <textarea class="text-box col-md-9" placeholder="Enter your review here"></textarea>
        <button type="button" class="btn btn-primary text-box-btn" onclick="postComment({{ movie.id }}, '{{ is_logged_in }}')">Comment</button>
      </div>
    </div>

    <div class="row movie-review">
      {% if review_page %}
        <div class="container review">
          {% for review in review_page %}
            <div class="review-item">
              <div class="d-flex">
                <div class="short-content pl-4">
                  <h5>
                    <i class="fa fa-user"></i>
                    <span><a href="{% url 'rango:reviews' review.user %}">{{ review.user }}</a></span>
                    {% if review.rating != -1 %}
                      <span class="ml-3 cr1">&nbsp{{ review.rating }}</span>
                    {% endif %}
                    <span class="ml-3 time">{{ review.time }}</span>
                  </h5>
                  <h4 class="cr1">{{ review.title }}</h4>
                  <div class="more">
                    <div class="text-wrap">
                      <div class="text">
                        {{ review.content }}
                      </div>
                      <div class="util">
                        <a class="unfold" href="#">(More)</a>
                        <a class="put" href="#">(Less)</a>
                      </div>
                    </div>
                    <div class="response">
                      <a class="fabulous" onclick="like({{ review.id }})" href="javascript:void(0)">
                        <i class="fa fa-thumbs-o-up" style="font-family: FontAwesome;"></i>
                        <span id="{{ review.id }}">{{ review.likes }}</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}

          <nav aria-label="Page navigation">
            <ul class="pagination justify-content-end">
              {% if review_page.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="{{ url_prefix }}{{ current_page|add:-1 }}">Previous</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" aria-disabled="true">Previous</a>
                </li>
              {% endif %}

              {% for i in page_range %}
                {% if i == current_page %}
                  <li class="page-item  active"><a class="page-link" href="#">{{ i }}</a></li>
                {% else %}
                  <li class="page-item"><a class="page-link" href="{{ url_prefix }}{{ i }}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}

              {% if review_page.has_next %}
                <li class="page-item">
                  <a class="page-link" href="{{ url_prefix }}{{ current_page|add:1 }}">Next</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" aria-disabled="true" href="#">Next</a>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      {% else %}
        <strong>No reviews</strong>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Restricted Page
{% endblock %}

{% block body_block %}
  <h1>Since you're logged in, you can see this text!</h1>
{% endblock %}

templates/rango/reviews.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{ list_title }}
{% endblock %}

{% block js_block %}
  <script src="{% static 'js/rango.js' %}" type="application/javascript"></script>
  <script src="{% static 'js/reviews.js' %}" type="application/javascript"></script>
{% endblock %}

{% block body_block %}
  <div class="review-body">
    <div class="display-4">{{ list_title }}</div>

    {% if review_page %}
      <div class="container review">
        {% for review in review_page %}
          <div class="review-item">
            <div class="d-flex">
              <div class="film">
                <a href="{% url 'rango:movie_detail' %}{{ review.movie.id }}">
                  <img class="" src="{{ MEDIA_URL }}movie_covers/{{ review.movie.imdb_id }}.jpg" alt="movie cover">
                </a>
              </div>
              <div class="short-content pl-4">
                <h5>
                  <i class="fa fa-user"></i>
                  <span><a href="{% url 'rango:reviews' review.user %}">{{ review.user }}</a></span>
                  <span class="ml-3 cr1">&nbsp{{ review.rating }}</span>
                  <span class="ml-3 time">{{ review.time }}</span>
                </h5>
                <h4 class="cr1">{{ review.title }}</h4>
                <div class="more">
                  <div class="text-wrap">
                    <div class="text">
                      {{ review.content }}
                    </div>
                    <div class="util">
                      <a class="unfold" href="#">(More)</a>
                      <a class="put" href="#">(Less)</a>
                    </div>
                  </div>
                  <div class="response">
                    <a class="fabulous" href="javascript:void(0)">
                      <i class="fa fa-thumbs-o-up" style="font-family: FontAwesome;"></i>
                      <span id="{{ review.id }}" onclick="like({{ review.id }})">{{ review.likes }}</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}

        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-end">
            {% if review_page.has_previous %}
              <li class="page-item">
                <a class="page-link" href="{{ url_prefix }}{{ current_page|add:-1 }}">Previous</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-disabled="true">Previous</a>
              </li>
            {% endif %}

            {% for i in page_range %}
              {% if i == current_page %}
                <li class="page-item  active"><a class="page-link" href="#">{{ i }}</a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="{{ url_prefix }}{{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}

            {% if review_page.has_next %}
              <li class="page-item">
                <a class="page-link" href="{{ url_prefix }}{{ current_page|add:1 }}">Next</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" aria-disabled="true" href="#">Next</a>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    {% else %}
      <strong>No reviews</strong>
    {% endif %}
  </div>
{% endblock %}